# Generated by Django 5.2.1 on 2025-06-06 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Main_Course',
            fields=[
                ('main_course_id', models.AutoField(primary_key=True, serialize=False)),
                ('main_course_name', models.CharField(blank=True, max_length=150, null=True)),
                ('main_course_cost', models.IntegerField(blank=True, null=True)),
                ('main_course_price', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('restaurant_id', models.AutoField(primary_key=True, serialize=False)),
                ('restaurant_name', models.TextField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('school_id', models.AutoField(primary_key=True, serialize=False)),
                ('school_name', models.CharField(choices=[('SPCC', "St. Paul's Co-educational College"), ('DGS', "Diocesan Girls' School"), ('HY', 'Heep Yunn School'), ('SMCC', "St. Mary's Canossian College"), ('MCS', 'Maryknoll Convent School(Secondary Section)'), ('SPCS', "St. Paul's Convent School"), ('LSC', 'La Salle College'), ('QC', "Queen's College"), ('HKTATH', 'Hong Kong Taoist Association Tang Hin Memorial Secondary School'), ('SKHTST', ' S.K.H. Tsang Shiu Tim Secondary School')], default='SPCC', max_length=10)),
                ('school_address', models.TextField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.UUIDField(primary_key=True, serialize=False)),
                ('order_date_time', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('confirm_payment', models.BooleanField(blank=True, null=True)),
                ('meal1', models.CharField(max_length=10)),
                ('meal2', models.CharField(max_length=10)),
                ('meals', models.ManyToManyField(to='order_app.main_course')),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_app.school')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('stid', models.AutoField(primary_key=True, serialize=False)),
                ('student_id', models.CharField(editable=False, max_length=20)),
                ('first_name', models.CharField(blank=True, max_length=60, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('date_of_birth', models.DateTimeField(blank=True, null=True)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('is_active', models.BooleanField()),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_app.school')),
            ],
        ),
    ]
