# Generated by Django 5.1.4 on 2025-06-08 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0003_main_course_restaurant_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main_course',
            name='restaurant_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='meals',
        ),
        migrations.RemoveField(
            model_name='order',
            name='school_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='school_id',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
        migrations.DeleteModel(
            name='Main_Course',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='School',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
