# Generated by Django 5.1.4 on 2025-06-08 09:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order_app', '0004_remove_main_course_restaurant_id_remove_order_meals_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main_Course',
            fields=[
                ('main_course_id', models.AutoField(primary_key=True, serialize=False)),
                ('main_course_name', models.CharField(blank=True, max_length=150, null=True)),
                ('main_course_cost', models.IntegerField(blank=True, null=True)),
                ('main_course_price', models.IntegerField(blank=True, null=True)),
                ('main_course_img', models.ImageField(null=True, upload_to='main_course')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('restaurant_id', models.AutoField(primary_key=True, serialize=False)),
                ('restaurant_name', models.TextField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('school_id', models.AutoField(primary_key=True, serialize=False)),
                ('school_name', models.CharField(choices=[('SPCC', "St. Paul's Co-educational College"), ('DGS', "Diocesan Girls' School"), ('HY', 'Heep Yunn School'), ('SMCC', "St. Mary's Canossian College"), ('MCS', 'Maryknoll Convent School(Secondary Section)'), ('SPCS', "St. Paul's Convent School"), ('LSC', 'La Salle College'), ('QC', "Queen's College"), ('HKTATH', 'Hong Kong Taoist Association Tang Hin Memorial Secondary School'), ('SKHTST', ' S.K.H. Tsang Shiu Tim Secondary School')], default='SPCC', max_length=10)),
                ('school_address', models.TextField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MealCombination',
            fields=[
                ('combination_id', models.AutoField(primary_key=True, serialize=False)),
                ('meal1', models.CharField(max_length=150)),
                ('meal2', models.CharField(max_length=150)),
                ('meal3', models.CharField(max_length=150)),
                ('meal4', models.CharField(max_length=150)),
                ('meal5', models.CharField(max_length=150)),
                ('main_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_app.main_course')),
            ],
        ),
        migrations.AddField(
            model_name='main_course',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_app.restaurant'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_date_time', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('confirm_payment', models.BooleanField(blank=True, null=True)),
                ('meals', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_app.mealcombination')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_app.school')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('stid', models.AutoField(primary_key=True, serialize=False)),
                ('student_id', models.CharField(editable=False, max_length=20)),
                ('first_name', models.CharField(blank=True, max_length=60, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('is_active', models.BooleanField()),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_app.school')),
            ],
        ),
    ]
