# Generated by Django 5.1.4 on 2025-06-08 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0005_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealcombination',
            name='meal1',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='mealcombination',
            name='meal2',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='mealcombination',
            name='meal3',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='mealcombination',
            name='meal4',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='mealcombination',
            name='meal5',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
