# Generated by Django 5.2.1 on 2025-06-10 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0006_alter_mealcombination_meal1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='meals',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_app.main_course'),
        ),
        migrations.DeleteModel(
            name='MealCombination',
        ),
    ]
