# Generated by Django 5.2.1 on 2025-06-10 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0007_alter_order_meals_delete_mealcombination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='meals',
        ),
        migrations.AddField(
            model_name='order',
            name='meal1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meal1', to='order_app.main_course'),
        ),
        migrations.AddField(
            model_name='order',
            name='meal2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meal2', to='order_app.main_course'),
        ),
        migrations.AddField(
            model_name='order',
            name='meal3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meal3', to='order_app.main_course'),
        ),
        migrations.AddField(
            model_name='order',
            name='meal4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meal4', to='order_app.main_course'),
        ),
        migrations.AddField(
            model_name='order',
            name='meal5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meal5', to='order_app.main_course'),
        ),
    ]
