# Generated by Django 5.2.1 on 2025-06-10 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0008_remove_order_meals_order_meal1_order_meal2_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
