# Generated by Django 5.2.1 on 2025-06-10 08:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0009_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_date_time', models.DateTimeField(blank=True, null=True)),
                ('confirm_payment', models.BooleanField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('meal1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meal1', to='order_app.main_course')),
                ('meal2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meal2', to='order_app.main_course')),
                ('meal3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meal3', to='order_app.main_course')),
                ('meal4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meal4', to='order_app.main_course')),
                ('meal5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meal5', to='order_app.main_course')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_app.school')),
            ],
        ),
    ]
