# Generated by Django 5.2.1 on 2025-06-11 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0011_alter_student_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='student_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='order_app.student'),
            preserve_default=False,
        ),
    ]
