# Generated by Django 5.2.1 on 2025-06-11 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0013_alter_order_student_name_alter_student_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='student_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_app.student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
