# Generated by Django 5.2.1 on 2025-06-11 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0014_alter_order_student_name_alter_student_first_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='price',
            new_name='total_price',
        ),
    ]
