# Generated by Django 5.2.1 on 2025-06-11 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0015_rename_price_order_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_course',
            name='main_course_cost',
            field=models.IntegerField(blank=True, default=20, null=True),
        ),
        migrations.AlterField(
            model_name='main_course',
            name='main_course_price',
            field=models.IntegerField(blank=True, default=60, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='meal1',
            field=models.ForeignKey(blank=True, default='叉燒蛋飯', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meal1', to='order_app.main_course'),
        ),
        migrations.AlterField(
            model_name='order',
            name='meal2',
            field=models.ForeignKey(blank=True, default='叉燒蛋飯', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meal2', to='order_app.main_course'),
        ),
        migrations.AlterField(
            model_name='order',
            name='meal3',
            field=models.ForeignKey(blank=True, default='叉燒蛋飯', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meal3', to='order_app.main_course'),
        ),
        migrations.AlterField(
            model_name='order',
            name='meal4',
            field=models.ForeignKey(blank=True, default='叉燒蛋飯', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meal4', to='order_app.main_course'),
        ),
        migrations.AlterField(
            model_name='order',
            name='meal5',
            field=models.ForeignKey(blank=True, default='叉燒蛋飯', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meal5', to='order_app.main_course'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, default='Payme', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.IntegerField(blank=True, default=300, null=True),
        ),
    ]
