# Generated by Django 5.1.4 on 2025-06-12 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0016_alter_main_course_main_course_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_course',
            name='main_course_img',
            field=models.ImageField(null=True, upload_to='main_course', verbose_name='Image'),
        ),
    ]
