# Generated by Django 5.2.1 on 2025-06-13 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0017_alter_main_course_restaurant_alter_order_meal1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_course',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_app.restaurant'),
        ),
        migrations.AlterField(
            model_name='order',
            name='meal1',
            field=models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meal1', to='order_app.main_course'),
        ),
        migrations.AlterField(
            model_name='order',
            name='meal2',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meal2', to='order_app.main_course'),
        ),
        migrations.AlterField(
            model_name='order',
            name='meal3',
            field=models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meal3', to='order_app.main_course'),
        ),
        migrations.AlterField(
            model_name='order',
            name='meal4',
            field=models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meal4', to='order_app.main_course'),
        ),
        migrations.AlterField(
            model_name='order',
            name='meal5',
            field=models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meal5', to='order_app.main_course'),
        ),
        migrations.AlterField(
            model_name='order',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_app.school'),
        ),
        migrations.AlterField(
            model_name='order',
            name='student_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_app.student'),
        ),
    ]
