# Generated by Django 5.1.4 on 2025-06-13 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0018_alter_main_course_restaurant_alter_order_meal1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='meal2',
            field=models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meal2', to='order_app.main_course'),
        ),
    ]
