# Generated by Django 5.2.1 on 2025-06-16 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0019_alter_order_meal2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='school',
        ),
    ]
